### PR TITLE
Reduce code duplication dispatching to main queue

### PR DESCRIPTION
**Pull request by Broich**
This PR reduces duplicated calls when dispatching completion handlers back to the main queue.

We can now pass a generic result type and en error object that is used in the majority of cases to a private helper function that takes over the job of calling the GCP API.

### CODE REVIEW

**Comment by marmelroy** [comment]
@Broich - does it make sense for disaptchOnMainQueue to be in the networking class? Maybe we can create a utilities class so things are more reusable/discoverable.

**Comment by Broich** [comment]
@marmelroy I think it's a good point. I moved the implementation into it's own util class.

**Comment by erikprice** [comment]
Swift has a built-in way to defer the execution of a function's parameters, called [@autoclosure](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html#//apple_ref/doc/uid/TP40014097-CH11-ID543). Something like (untested)…
```
extension DispatchQueue {
  static func dispatchOnMain(defer deferredClosure: @autoclosure(escaping) () -> Void) {
    self.main.async(deferredClosure)
  }
}

// Call site examples:
DispatchQueue.dispatchOnMain(defer: completion(session, nil))
DispatchQueue.dispatchOnMain(defer: completion(nil, error))
DispatchQueue.dispatchOnMain(defer: completion(nil, LoginError.configurationMissing))
DispatchQueue.dispatchOnMain(defer: completion(profileResponse?.identifier))
```
But I have to confess that I'm not seeing how any of these alternatives reduce code duplication. We're still saying the same thing in each approach, albeit in fewer tokens. What's more, a future maintainer now has to double-check that these helper functions don't have additional effects. `DispatchQueue.main.async { }` is widely recognized/understood. Though maybe I'm missing some deeper problem that this is intended to address?

**Comment by Broich** [comment]
@erikprice great to learn about autoclosures and yes an extension looks more elegant and _swifty_. 
The intention of this PR was to reduce the number of repetitive `Dispatch.main.async` calls.

**Comment by Broich** [comment]
Updated the PR with the autoclosure and extension approach. I personally like this as a more elegant solution. I disagree (at least in this case) that it would add maintenance cost since we're using what's been given to us by Swift without adding logic of our own but will leave it for @marmelroy to decide what to do with this 😀.

**Pull request closed without merging**
