### PR TITLE
Allow configure to set show_dialog value

### LINKED ISSUE #15: Allow show_dialog to be false
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
`show_dialog` is hardcoded to true. It should be able to be set by the developer.

### Versions
1.0.6

### Severity
Minor

### PR DESCRIPTION
**Pull request by arirawr**
Defaults to true.

Fixes #15

### CODE REVIEW

**Comment by marmelroy** [comment]
@arirawr - cool improvement but it breaks a couple of unit tests

**Comment by arirawr** [comment]
Woops - I'll fix that.

**Comment by arirawr** [comment]
Can I get a review on this @marmelroy? :)

**Comment by marmelroy** [comment]
Sorry @arirawr - was on vacation. Looks good.

**Pull request merged**
